document.write([
	"<table border='1'>",
		"<tr>",
			"<td colspan='2'>",
				'Nguyen Cao Vu <a href="login.html">Logout</a>',
				'<button>Tieng viet</button>',
				'<button>English</button>',
			"</td>",
		"</tr>",
		"<tr>",
			"<td>",
				"<button onclick='location.href=\"seasonList.html\"'>Seasons</button><br>",
				"<button onclick='location.href=\"tournamentList.html\"'>Tournaments</button><br>",
				"<button onclick='location.href=\"teamList.html\"'>Teams</button><br>",
				"<button onclick='location.href=\"matchList.html\"'>Matches</button><br>",
				"<button>Predictions</button><br>",
				"<button>Packages</button><br>",
				"<button>Clients</button><br>",
				"<button>Transactions</button><br>",
				"<button>Notices</button><br>",
				"<button>Advertisements</button><br>",
				"<button>Moderators</button><br>",
				"<button>VIPs</button><br>",
				"<button>Configurations</button><br>",
				"<button>Statistics</button><br>",
			"</td>",
			"<td style='width:920px; vertical-align:top'>"
].join(''));