document.write([
	"<table border='1'>",
		"<tr>",
			"<td colspan='2'>",
				'Nguyen Cao Vu <a href="login.html">Logout</a>',
				'<button>Tieng viet</button>',
				'<button>English</button>',
			"</td>",
		"</tr>",
		"<tr>",
			"<td>",
				"<button onclick='location.href=\"seasonList.html\"'>Seasons</button><br>",
				"<button onclick='location.href=\"tournamentList.html\"'>Tournaments</button><br>",
				"<button onclick='location.href=\"teamList.html\"'>Teams</button><br>",
				"<button onclick='location.href=\"matchList.html\"'>Matches</button><br>",
				"<button onclick='location.href=\"predictionList.html\"'>Predictions</button><br>",
				"<button onclick='location.href=\"packageList.html\"'>Packages</button><br>",
				"<button onclick='location.href=\"userList.html\"'>Clients</button><br>",
				"<button onclick='location.href=\"transactionList.html\"'>Transactions</button><br>",
				"<button onclick='location.href=\"noticeList.html\"'>Notices</button><br>",
				"<button onclick='location.href=\"adList.html\"'>Advertisements</button><br>",
				"<button onclick='location.href=\"modList.html\"'>Moderators</button><br>",
				"<button>VIPs</button><br>",
				"<button>Configurations</button><br>",
				"<button onclick='location.href=\"statistics.html\"'>Statistics</button><br>",
			"</td>",
			"<td style='width:920px; vertical-align:top'>"
].join(''));