document.write([
	"WIN: 3<br>",
	"LOOSE: 1<br>",
	"DRAW: 2<br>",
	"WINNING RATE = 50%<br>",
	"<table border='1'>",
		"<tr style='font-weight:bold;'>",
			"<td>Host team</td>",
			"<td>Guest team</td>",
			"<td>Handicap</td>",
			"<td>Date time</td>",
			"<td>Price type</td>",
			"<td>Prediction type</td>",
			"<td>Winner</td>",
			"<td>Total score</td>",
			"<td>Over/lower</td>",
			"<td>Final score</td>",
			"<td>Result</td>",
		"</tr>",
		"<tr>",
			"<td>Manchester United</td>",
			"<td>Chelsea</td>",
			"<td>1/2-0</td>",
			"<td>19:00 Feb 12, 2010</td>",
			"<td>King</td>",
			"<td>Winner</td>",
			"<td>Manchester United</td>",
			"<td>-</td>",
			"<td>-</td>",
			"<td>1-0</td>",
			"<td>WIN</td>",	
		"</tr>",
		"<tr>",
			"<td>Vietnam</td>",
			"<td>Thailand</td>",
			"<td>4 1/2-0</td>",
			"<td>19:30 Feb 13, 2010</td>",
			"<td>Free</td>",
			"<td>Over/lower</td>",
			"<td>-</td>",
			"<td>10</td>",
			"<td>Over</td>",
			"<td>5-4</td>",
			"<td>LOOSE</td>",
		"</tr>",
		"<tr>",
			"<td>Villa</td>",
			"<td>Ailato</td>",
			"<td>1/2-0</td>",
			"<td>19:00 Feb 12, 2010</td>",
			"<td>King</td>",
			"<td>Winner</td>",
			"<td>Ailato</td>",
			"<td>-</td>",
			"<td>-</td>",
			"<td>0-0</td>",
			"<td>WIN</td>",
		"</tr>",
		"<tr>",
			"<td>Barca</td>",
			"<td>Real Madrid</td>",
			"<td>1-0</td>",
			"<td>20:00 Feb 14, 2010</td>",
			"<td>Occean</td>",
			"<td>Winner</td>",
			"<td>Real Madrid</td>",
			"<td>-</td>",
			"<td>-</td>",
			"<td>1-0</td>",
			"<td>DRAW</td>",
		"</tr>",
		"<tr>",
			"<td>Inter miland</td>",
			"<td>HAGL FC</td>",
			"<td>0-1 1/2</td>",
			"<td>18:30 March 20, 2010</td>",
			"<td>King</td>",
			"<td>Over/lower</td>",
			"<td>-</td>",
			"<td>4</td>",
			"<td>Lower</td>",
			"<td>1-2</td>",
			"<td>WIN</td>",
		"</tr>",
		"<tr>",
			"<td>Arab Saudi</td>",
			"<td>Japan</td>",
			"<td>0-2</td>",
			"<td>19:00 March 20, 2010</td>",
			"<td>Occean</td>",
			"<td>Winner</td>",
			"<td>Japan</td>",
			"<td>-</td>",
			"<td>-</td>",
			"<td>0-2</td>",
			"<td>DRAW</td>",
		"</tr>",
	"</table>",
].join(''));