document.write([
	'<select>',
		'<option class="" value="-12">(GMT -12:00) Eniwetok, Kwajalein</option>',
		'<option class="" value="-11">(GMT -11:00) Midway Island, Samoa</option>',
		'<option class="" value="-10">(GMT -10:00) Hawaii</option>',
		'<option class="" value="-9">(GMT -9:00) Alaska</option>',
		'<option class="" value="-8">(GMT -8:00) Pacific Time (US &amp; Canada)</option>',
		'<option class="" value="-7">(GMT -7:00) Mountain Time (US &amp; Canada)</option>',
		'<option class="" value="-6">(GMT -6:00) Central Time (US &amp; Canada), Mexico City</option>',
		'<option class="" value="-5">(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima</option>',
		'<option class="" value="-4.5">(GMT -4:30) Caracas</option>',
		'<option class="" value="-4">(GMT -4:00) Atlantic Time (Canada), La Paz, Santiago</option>',
		'<option class="" value="-3.5">(GMT -3:30) Newfoundland</option>',
		'<option class="" value="-3">(GMT -3:00) Brazil, Buenos Aires, Georgetown</option>',
		'<option class="" value="-2">(GMT -2:00) Mid-Atlantic</option>',
		'<option class="" value="-1">(GMT -1:00 hour) Azores, Cape Verde Islands</option>',
		'<option class="" value="0">(GMT) Western Europe Time, London, Lisbon, Casablanca</option>',
		'<option class="" value="1">(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris</option>',
		'<option class="" value="2">(GMT +2:00) Kaliningrad, South Africa, Cairo</option>',
		'<option class="" value="3">(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg</option>',
		'<option class="" value="3.5">(GMT +3:30) Tehran</option>',
		'<option class="" value="4">(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi</option>',
		'<option class="" value="4.5">(GMT +4:30) Kabul</option>',
		'<option class="" value="5">(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent</option>',
		'<option class="" value="5.5">(GMT +5:30) Mumbai, Kolkata, Chennai, New Delhi</option>',
		'<option class="" value="5.75">(GMT +5:45) Kathmandu</option>',
		'<option class="" value="6">(GMT +6:00) Almaty, Dhaka, Colombo</option>',
		'<option class="" value="6.5">(GMT +6:30) Yangon, Cocos Islands</option>',
		'<option selected="selected" class="" value="7">(GMT +7:00) Bangkok, HÅEN?i, Jakarta</option>',
		'<option class="" value="8">(GMT +8:00) Beijing, Perth, Singapore, Hong Kong</option>',
		'<option class="" value="9">(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk</option>',
		'<option class="" value="9.5">(GMT +9:30) Adelaide, Darwin</option>',
		'<option class="" value="10">(GMT +10:00) Eastern Australia, Guam, Vladivostok</option>',
		'<option class="" value="11">(GMT +11:00) Magadan, Solomon Islands, New Caledonia</option>',
		'<option class="" value="12">(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka</option>',
	'</select>'
].join(''));