document.write(
	[
		"<b>MENU</b>",
		"<br>",
		"<button onclick='location.href=\"packageList.html\"'>Buy package</button>",
		"<br>",
		"<button onclick='location.href=\"notifyTransfer.html\"'>Transfer money</button>",
		"<br>",
		"<button onclick='location.href=\"notifyDraw.html\"'>Draw money</button>",
		"<br>",
		"<button onclick='location.href=\"transactionList.html\"'>All transaction</button>",
		"<br>",
		"<button onclick='location.href=\"statistics.html\"'>Statistics</button>",
		"<br>",
		"<br>",
		"<b>NOTICE</b>",
		"<div style='border:1;background-color:yellow;width:150px;'>",
			"Add 10 King predictions to all VIP accounts",
		"</div>",
		"<br>",
		"<br>",
		"<b>SUPPORTERS</b>",
		"<br>",
		"<img src='yahooonline.gif'/>anh Binh",
		"<br>",
		"<img src='yahoooffline.jpeg'/>Cao Vu",
	].join("")
);